import { UserProfile } from '../../types/user';
import { DailyVitals, HealthScoreDetails, MealItem, WorkoutItem } from '../../types/health';
import { MedicalReport } from '../../types/report';
import { SevenDayDietPlan } from '../../types/ai';

export const DEMO_USER_PROFILE: UserProfile = {
  id: 'aarav_demo',
  name: 'Aarav',
  phone: '+919876543210',
  healthId: '91-4523-8871-0021',
  age: 21,
  gender: 'Male',
  heightCm: 175,
  weightKg: 68,
  bmi: 22.2,
  healthGoals: ['Fitness & Strength', 'Balanced Indian Nutrition', 'Consistent Hydration'],
  dietaryPreferences: ['Vegetarian'],
  allergies: [],
  medicalConditions: [],
  medications: [],
  foodPreferences: {
    preferred: ['Dal Roti', 'Paneer Rice', 'Vegetable Poha', 'Moong Dal Chilla', 'Sprouted Chaat'],
    disliked: ['Bitter Gourd (Karela)', 'Extremely sweet desserts'],
    spiciness: 'medium',
    regionalCuisine: ['North Indian', 'South Indian'],
  },
  language: 'English',
  familyMembers: [
    {
      id: 'fam-mom-1',
      name: 'Sunita (Mother)',
      relation: 'Parent',
      age: 52,
      uniqueFamilyId: 'MEDIBUD-MOM-52',
      permissions: {
        profile: true,
        reports: true,
        medications: true,
        vitals: true,
        plans: true,
      },
    },
    {
      id: 'fam-grandpa-2',
      name: 'Ramesh (Grandfather)',
      relation: 'Other',
      age: 78,
      uniqueFamilyId: 'MEDIBUD-DADA-78',
      permissions: {
        profile: true,
        reports: true,
        medications: true,
        vitals: true,
        plans: false,
      },
    },
  ],
  isSeniorMode: false,
  onboardingCompleted: true,
  createdAt: '2026-09-01T10:00:00Z',
};

export const DEMO_VITALS: DailyVitals = {
  bloodPressure: '120/80',
  heartRate: 72,
  bloodGlucose: '94 mg/dL',
  spo2: 98,
  weightKg: 68,
  lastUpdated: 'Today, 8:00 AM',
};

export const DEMO_HEALTH_SCORE: HealthScoreDetails = {
  score: 82,
  category: 'Optimal',
  breakdown: {
    hydration: 85,
    nutrition: 80,
    activity: 82,
    sleep: 81,
  },
  disclaimer: 'Your score reflects your recent wellness habits and is not a medical assessment.',
};

export const DEMO_RECENT_MEALS: MealItem[] = [
  {
    id: 'meal-1',
    name: '2 Moong Dal Chillas + Mint Coriander Chutney',
    mealType: 'Breakfast',
    calories: 340,
    proteinG: 16,
    carbsG: 42,
    fatG: 10,
    isEstimated: false,
    timestamp: '8:30 AM',
  },
  {
    id: 'meal-2',
    name: '2 Phulkas + Paneer Bhurji + Yellow Dal + Cucumber Salad',
    mealType: 'Lunch',
    calories: 550,
    proteinG: 26,
    carbsG: 68,
    fatG: 19,
    isEstimated: false,
    timestamp: '1:15 PM',
  },
  {
    id: 'meal-3',
    name: 'Roasted Makhana + Warm Green Tea',
    mealType: 'Snack',
    calories: 140,
    proteinG: 4,
    carbsG: 22,
    fatG: 3,
    isEstimated: false,
    timestamp: '5:00 PM',
  },
];

export const DEMO_WORKOUTS: WorkoutItem[] = [
  { id: 'wo-1', title: 'Morning Brisk Walk (3.5 km)', category: 'Walking', durationMinutes: 35, completed: true, date: 'Today' },
  { id: 'wo-2', title: 'Core Stability & Push-ups', category: 'Strength', durationMinutes: 20, completed: true, date: 'Today' },
  { id: 'wo-3', title: 'Evening Post-Dinner Walk', category: 'Walking', durationMinutes: 15, completed: false, date: 'Today' },
];

export const DEMO_SAMPLE_REPORT: MedicalReport = {
  id: 'rep-cbc-2026',
  userId: 'aarav_demo',
  title: 'Annual Health Check: CBC & Metabolic Profile',
  reportType: 'Pathology',
  date: '12 March 2026',
  doctorOrLabName: 'Dr. Lal PathLabs, Delhi NCR',
  testResults: [
    { testName: 'Hemoglobin', value: '14.8', unit: 'g/dL', referenceRange: '13.0 - 17.0', status: 'NORMAL' },
    { testName: 'Total WBC Count', value: '7,200', unit: '/uL', referenceRange: '4,000 - 11,000', status: 'NORMAL' },
    { testName: 'Platelet Count', value: '240,000', unit: '/uL', referenceRange: '150,000 - 450,000', status: 'NORMAL' },
    { testName: 'Fasting Blood Sugar', value: '92', unit: 'mg/dL', referenceRange: '70 - 100', status: 'NORMAL' },
    { testName: 'HbA1c', value: '5.4', unit: '%', referenceRange: '< 5.7', status: 'NORMAL' },
    { testName: 'Total Cholesterol', value: '182', unit: 'mg/dL', referenceRange: '< 200', status: 'NORMAL' },
    { testName: 'HDL (Good) Cholesterol', value: '52', unit: 'mg/dL', referenceRange: '> 40', status: 'NORMAL' },
    { testName: 'LDL (Bad) Cholesterol', value: '104', unit: 'mg/dL', referenceRange: '< 100', status: 'HIGH' },
    { testName: 'Triglycerides', value: '130', unit: 'mg/dL', referenceRange: '< 150', status: 'NORMAL' },
  ],
  aiExplanation:
    'Your red and white blood cell markers indicate robust immune health. Fasting blood sugar and HbA1c reflect optimal metabolic sensitivity. Your LDL cholesterol is 104 mg/dL (slightly above the strict 100 mg/dL target), which can be smoothly modulated with regular cardiovascular activity and fiber-rich meals.',
  lifestyleRecommendations: [
    'Maintain daily brisk walking or light jogging to elevate HDL and optimize LDL.',
    'Include soluble prebiotic fibers like oats, fenugreek (methi), and lentils in your diet.',
    'Keep your daily water intake above 2.5L to support hydration and cellular renewal.',
  ],
  questionsForDoctor: [
    'Is a follow-up lipid screening indicated in 12 months?',
    'Are there specific aerobic intensity zones recommended for LDL control?',
  ],
  rawTextPreview:
    'Patient: Aarav. Age: 21. Tests: CBC, Fasting Blood Sugar, HbA1c, Lipid Profile. All markers normal except borderline LDL 104 mg/dL.',
  chunksIndexed: 3,
};

export const DEMO_DIET_PLAN: SevenDayDietPlan = {
  title: '7-Day Vitality & Strength Indian Meal Plan for Aarav',
  targetDailyCalories: 1950,
  macroTargets: { proteinG: 85, carbsG: 240, fatG: 50 },
  days: [
    {
      dayNumber: 1,
      dayName: 'Monday - Energize',
      meals: {
        breakfast: {
          name: 'Vegetable Poha with roasted peanuts + Warm lemon water',
          portion: '1 medium plate (200g)',
          approxCalories: 320,
          proteinG: 8,
          carbsG: 52,
          fatG: 9,
          notes: 'Cook with minimal cold-pressed oil; garnish with fresh coriander.',
          alternatives: ['Oats Upma with carrots & peas', 'Moong Dal Chilla'],
        },
        lunch: {
          name: '2 Phulkas + Palak Paneer + Yellow Moong Dal + Cucumber Salad',
          portion: 'Standard thali',
          approxCalories: 560,
          proteinG: 22,
          carbsG: 72,
          fatG: 18,
          notes: 'High bioavailable iron and complete vegetarian protein.',
          alternatives: ['Paneer Rice Bowl', 'Ragi Roti with Paneer Bhurji'],
        },
        eveningSnack: {
          name: 'Roasted Makhana with rock salt + Tulsi Green Tea',
          portion: '1 small bowl (30g)',
          approxCalories: 130,
          proteinG: 4,
          carbsG: 22,
          fatG: 2,
          notes: 'Antioxidant-rich clean crunchy snack.',
          alternatives: ['Sprouted Moong Chaat', 'Roasted Chana'],
        },
        dinner: {
          name: 'Warm Moong Dal Khichdi with fresh curd & steamed vegetables',
          portion: '1 large bowl',
          approxCalories: 450,
          proteinG: 16,
          carbsG: 68,
          fatG: 10,
          notes: 'Easy to digest; supports sound, restorative sleep.',
          alternatives: ['Dal Dalia Khichdi', 'Sautéed Paneer & Vegetable Broth'],
        },
      },
    },
    {
      dayNumber: 2,
      dayName: 'Tuesday - Strength',
      meals: {
        breakfast: {
          name: '2 Moong Dal Chillas filled with grated paneer + mint chutney',
          portion: '2 chillas',
          approxCalories: 360,
          proteinG: 18,
          carbsG: 40,
          fatG: 12,
          notes: 'Power breakfast with sustained energy release.',
          alternatives: ['Paneer Stuffed Besan Chilla', 'Multigrain Toast with peanut butter'],
        },
        lunch: {
          name: 'Brown Basmati Rice + Rajma Masala + Kachumber salad',
          portion: '1 cup rice + 1 cup rajma',
          approxCalories: 580,
          proteinG: 20,
          carbsG: 88,
          fatG: 11,
          notes: 'Balanced amino acids from classic Indian legume-grain synergy.',
          alternatives: ['Chole with Multi-seed Roti', 'Lobia Curry with brown rice'],
        },
        eveningSnack: {
          name: 'Soaked almonds (8) & walnuts (2) + Tender Coconut Water',
          portion: '1 serving',
          approxCalories: 150,
          proteinG: 5,
          carbsG: 6,
          fatG: 13,
          notes: 'Natural electrolytes and brain-healthy omega-3s.',
          alternatives: ['Roasted Chana', 'Fresh seasonal fruit'],
        },
        dinner: {
          name: '2 Jowar Rotis + Baingan Bharta + Masoor Dal',
          portion: '2 rotis + sides',
          approxCalories: 480,
          proteinG: 17,
          carbsG: 74,
          fatG: 9,
          notes: 'Gluten-free millet dinner promoting steady blood sugar.',
          alternatives: ['Bajra Roti with Methi Paneer', 'Vegetable Stew with Appam'],
        },
      },
    },
    {
      dayNumber: 3,
      dayName: 'Wednesday - Fiber & Gut Health',
      meals: {
        breakfast: {
          name: '3 Steamed Idlis + Mixed Vegetable Sambar + Coconut Chutney (1 tsp)',
          portion: '3 idlis',
          approxCalories: 310,
          proteinG: 10,
          carbsG: 58,
          fatG: 4,
          notes: 'Fermented live enzymes nurture the gut microbiome.',
          alternatives: ['Plain Rava Dosa with sambar', 'Pesarattu'],
        },
        lunch: {
          name: '2 Multigrain Rotis + Soya Chunk Curry + Fresh Garden Salad',
          portion: 'Standard meal',
          approxCalories: 540,
          proteinG: 26,
          carbsG: 65,
          fatG: 14,
          notes: 'Plant-protein powerhouse meal.',
          alternatives: ['Tofu Tikka Masala with rotis', 'Dal Tadka with Jeera Rice'],
        },
        eveningSnack: {
          name: 'Boiled Sweet Corn Chaat with chaat masala & lemon',
          portion: '1 cup',
          approxCalories: 140,
          proteinG: 4,
          carbsG: 28,
          fatG: 2,
          notes: 'Rich in lutein and prebiotic fibers.',
          alternatives: ['Sprouts Bhel', 'Cucumber sticks with curd dip'],
        },
        dinner: {
          name: 'Lauki Kofta in light gravy + 2 Phulkas + Sprouted Dal',
          portion: 'Standard serving',
          approxCalories: 460,
          proteinG: 15,
          carbsG: 68,
          fatG: 11,
          notes: 'Cooling and light on the digestive tract.',
          alternatives: ['Tinda Masala with Phulkas', 'Clear Vegetable Soup with paneer'],
        },
      },
    },
    {
      dayNumber: 4,
      dayName: 'Thursday - Metabolic Harmony',
      meals: {
        breakfast: {
          name: 'Warm Spiced Oatmeal with Chia seeds & chopped almonds',
          portion: '1 large bowl',
          approxCalories: 340,
          proteinG: 11,
          carbsG: 54,
          fatG: 10,
          notes: 'Beta-glucan fibers support healthy cholesterol balance.',
          alternatives: ['Dalia Porridge with milk & figs', 'Besan Toast with mint chutney'],
        },
        lunch: {
          name: '2 Phulkas + Paneer Tikka Masala + Yellow Moong Dal + Salad',
          portion: 'Standard thali',
          approxCalories: 570,
          proteinG: 23,
          carbsG: 70,
          fatG: 17,
          notes: 'Satisfying midday fuel preventing afternoon lethargy.',
          alternatives: ['Matar Paneer with Jeera Rice', 'Chana Masala with rotis'],
        },
        eveningSnack: {
          name: 'Roasted Peanuts & Chana with green tea',
          portion: '30g',
          approxCalories: 150,
          proteinG: 6,
          carbsG: 14,
          fatG: 8,
          notes: 'Traditional mineral and protein snack.',
          alternatives: ['Murmura Bhel', 'Pumpkin and sunflower seeds'],
        },
        dinner: {
          name: 'Methi Theplas (2) + Low-fat Curd + Boiled Dal',
          portion: '2 theplas',
          approxCalories: 440,
          proteinG: 14,
          carbsG: 62,
          fatG: 12,
          notes: 'Fenugreek leaves aid insulin sensitivity.',
          alternatives: ['Palak Paratha with curd', 'Vegetable Dalia Khichdi'],
        },
      },
    },
    {
      dayNumber: 5,
      dayName: 'Friday - Vitality',
      meals: {
        breakfast: {
          name: 'Sprouted Moong Chaat with pomegranate arils & lime',
          portion: '1 large bowl (250g)',
          approxCalories: 290,
          proteinG: 15,
          carbsG: 46,
          fatG: 3,
          notes: 'Living sprouts provide high bioavailability of vitamins.',
          alternatives: ['Chana Chaat', 'Paneer Sandwich on sourdough'],
        },
        lunch: {
          name: 'Vegetable Biryani with Soya Chunks + Mint Raita',
          portion: '1.5 cups',
          approxCalories: 580,
          proteinG: 24,
          carbsG: 82,
          fatG: 14,
          notes: 'Aromatic Friday lunch with complete vegetarian proteins.',
          alternatives: ['Paneer Pulao with raita', 'Dal Makhani (light) with 2 Rotis'],
        },
        eveningSnack: {
          name: 'Chaas (Spiced Buttermilk) with roasted cumin + 1 Apple',
          portion: '1 tall glass',
          approxCalories: 95,
          proteinG: 3,
          carbsG: 12,
          fatG: 2,
          notes: 'Cooling probiotic beverage.',
          alternatives: ['Coconut water', 'Lemon mint water'],
        },
        dinner: {
          name: '2 Phulkas + Bhindi Masala + Panchmel Dal',
          portion: 'Standard meal',
          approxCalories: 470,
          proteinG: 16,
          carbsG: 70,
          fatG: 12,
          notes: 'Okra provides soluble mucilaginous fiber.',
          alternatives: ['Tori Curry with Phulkas', 'Clear Vegetable Soup with paneer'],
        },
      },
    },
    {
      dayNumber: 6,
      dayName: 'Saturday - Active Weekend',
      meals: {
        breakfast: {
          name: '2 Paneer Parathas (light ghee) + 1 cup Plain Curd',
          portion: '2 parathas',
          approxCalories: 420,
          proteinG: 19,
          carbsG: 50,
          fatG: 15,
          notes: 'Hearty weekend breakfast for active training.',
          alternatives: ['Aloo Methi Paratha with curd', 'Cheela with paneer'],
        },
        lunch: {
          name: 'Curd Rice with tempered mustard seeds + 1 cup Dal Tadka',
          portion: '1 bowl curd rice + dal',
          approxCalories: 510,
          proteinG: 16,
          carbsG: 78,
          fatG: 13,
          notes: 'Soothing and restorative for intestinal wellness.',
          alternatives: ['Lemon Rice with dal', 'Bisi Bele Bath with raita'],
        },
        eveningSnack: {
          name: 'Roasted sunflower seeds & raisins + Green tea',
          portion: '25g',
          approxCalories: 130,
          proteinG: 4,
          carbsG: 14,
          fatG: 7,
          notes: 'Zinc and magnesium rich snack.',
          alternatives: ['Roasted Makhana', 'Steamed Dhokla (2 pieces)'],
        },
        dinner: {
          name: 'Grilled Vegetable & Paneer Skewers + Tomato Basil Soup',
          portion: '1 plate skewers + soup',
          approxCalories: 420,
          proteinG: 20,
          carbsG: 32,
          fatG: 18,
          notes: 'Low carb, light dinner before restful sleep.',
          alternatives: ['Paneer Salad Bowl', 'Moong Dal Soup with stir-fry'],
        },
      },
    },
    {
      dayNumber: 7,
      dayName: 'Sunday - Nourish & Reset',
      meals: {
        breakfast: {
          name: 'Steamed Dhokla (3 pieces) + Green Chutney + Sweet Lime',
          portion: '3 pieces',
          approxCalories: 280,
          proteinG: 9,
          carbsG: 50,
          fatG: 4,
          notes: 'Light fermented delicacy.',
          alternatives: ['Appam with vegetable stew', 'Khandvi with green tea'],
        },
        lunch: {
          name: 'Sunday Thali: 2 Phulkas, Light Paneer Butter Masala, Dal, Rice, Salad',
          portion: 'Balanced mindful portion',
          approxCalories: 620,
          proteinG: 22,
          carbsG: 84,
          fatG: 18,
          notes: 'Comforting Sunday homestyle lunch.',
          alternatives: ['Chole with Multi-grain Roti', 'Dum Aloo with Rotis'],
        },
        eveningSnack: {
          name: 'Fresh Tender Coconut Water',
          portion: '1 coconut',
          approxCalories: 60,
          proteinG: 1,
          carbsG: 13,
          fatG: 0.5,
          notes: 'Cellular hydration and natural potassium.',
          alternatives: ['Herbal chamomile tea', 'Thin salted chaas'],
        },
        dinner: {
          name: 'Healing Turmeric Moong Dal Soup + Sautéed greens & 1 Phulka',
          portion: '1 large bowl soup + 1 roti',
          approxCalories: 380,
          proteinG: 15,
          carbsG: 58,
          fatG: 7,
          notes: 'Gentle detoxifying reset meal preparing for the week.',
          alternatives: ['Clear veg broth with paneer', 'Dalia soup'],
        },
      },
    },
  ],
  dietitianRationale:
    'This plan integrates authentic Indian staple grains (wheat, brown rice, jowar, poha), high-quality vegetarian proteins (paneer, moong dal, rajma, soya), and prebiotic vegetable fibers. Spicing emphasizes digestive carminatives (jeera, hing, turmeric, ginger) to minimize bloating and enhance micronutrient absorption.',
  disclaimer: 'AI can make mistakes, so always double check important health information with a qualified healthcare professional.',
};
